# UI Mockup Generation Keyword Configuration

# Page type detection keywords
page_type_keywords:
  landing:
    - "landing"
    - "homepage"
    - "home"
    - "main page"
  login:
    - "login"
    - "signin"
    - "sign in"
    - "authentication"
    - "auth"
  signup:
    - "signup"
    - "sign up"
    - "register"
    - "registration"
    - "create account"
  profile:
    - "profile"
    - "user profile"
    - "account"
    - "user account"
    - "my account"
  about:
    - "about"
    - "about us"
    - "about page"
    - "company info"

# Intent detection keywords
intent_keywords:
  create_ui_mockup:
    - "create"
    - "build"
    - "make"
    - "generate"
    - "design"
  requirements_analysis:
    - "requirements"
    - "analyze"
    - "specification"
  template_recommendation:
    - "recommend"
    - "suggest"
    - "show templates"
  template_selection:
    - "select"
    - "choose"
    - "pick"
  editing:
    - "edit"
    - "modify"
    - "change"
  report:
    - "report"
    - "summary"
    - "export"
  general:
    - "help"
    - "hello"
    - "hi"

# Related categories for fallback
related_categories:
  about:
    - "landing"
    - "profile"
  login:
    - "signup"
    - "profile"
  signup:
    - "login"
    - "profile"
  profile:
    - "about"
    - "login"
  landing:
    - "about"
    - "profile"

# Design style keywords
design_style_keywords:
  modern_styles:
    - "modern"
    - "contemporary"
    - "sleek"
    - "clean"
  professional_styles:
    - "professional"
    - "business"
    - "corporate"
    - "formal"
  creative_styles:
    - "creative"
    - "artistic"
    - "unique"
    - "innovative"

# Component keywords
component_keywords:
  form_components:
    - "form"
    - "input"
    - "button"
    - "field"
  navigation_components:
    - "navigation"
    - "menu"
    - "navbar"
    - "header"
  content_components:
    - "content"
    - "text"
    - "image"
    - "section"

# Default values
default_values:
  max_templates: 5
  fallback_category: "landing"
  max_questions: 3